name: ci-golang-workflow
on: 
  pull_request:
    branches:
      - develop

jobs:
  
  check-application:

    strategy:
      matrix:
        go: ['1.14','1.15']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: go test
      - run: go run math.go

##Fazendo o Docker dentro do CI

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

##utilizando o Docker Username e Token para Realizar a config
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -  name: Build and push
      #Podendo colocar esse docker em outro step por isso o ID
         id : docker_build
         uses: docker/build-push-action@v3
         with:
          push: false
          tags: jeanribeiro1813/testeci-go:latest